name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute tests
        run: ./gradlew test

      - name: Code style
        run: ./gradlew ktfmtCheck

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/test-results/**/TEST-*.xml"
        if: always()

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@27bb264e040efceeae9469a5956785c27c6997f4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: true
          updateComment: true

      - name: Code Coverage
        id: jacoco
        uses: madrapps/jacoco-report@cae93f61ea553f8babe9d8c1e365c1ce5cece922
        with:
          paths: |
            "adapter/build/reports/jacoco/test/jacocoTestReport.xml"
            "core/build/reports/jacoco/test/jacocoTestReport.xml"
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: '80'
          min-coverage-changed-files: '80'
          title: Code Coverage
          update-comment: true
