name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Execute tests
        run: ./gradlew test

      - name: Code style
        run: ./gradlew ktfmtCheck

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/test-results/**/TEST-*.xml"
        if: always()
